/**
 * Client-side verification that an address the vault handed back is really
 * backed by shares on `threshold` or more independent signer nodes.
 *
 * # The gap this closes
 *
 * Create returns an address on the frontend's word alone. A compromised
 * frontend could skip the ceremony entirely, generate a key it knows, hand out
 * that address, and sign for it alone forever — the caller funds a wallet whose
 * threshold never existed. Distributed key generation makes that harder, because
 * the honest path really does put one share on each host, but nothing FORCES the
 * frontend down that path and nothing PROVES to the caller that it went.
 *
 * # Why node identity keys, and not the wallet's own key
 *
 * A signature by the new wallet's group key proves nothing: whoever holds a solo
 * key for that address can produce one too, which is exactly the attacker being
 * guarded against. So each signer node holds a long-term identity key, and
 * callers learn those public keys OUT OF BAND — from their own configuration,
 * never from the response being verified. That out-of-band step is not
 * incidental; it is what stops the caller from asking the vault whether the
 * vault is honest.
 *
 * This is a port of the Go `attest` package. The digest construction has to
 * match it byte for byte or verification silently never passes, so the tests run
 * against fixtures generated by the Go implementation rather than against a
 * second reading of the same prose.
 */
import { secp256k1 } from '@noble/curves/secp256k1';
import { keccak_256 } from '@noble/hashes/sha3';

/** Separates this signature from every other use of a node key, so an
 * attestation can never be replayed as some other kind of assertion. */
const DOMAIN = 'hypercyber-vault-wallet-attestation-v1';

const SIGNATURE_LENGTH = 65;
const COMPRESSED_PUBKEY_LENGTH = 33;

/** Bytes accepted anywhere this module wants a byte string: raw, or hex with or
 * without a `0x` prefix. */
export type ByteInput = Uint8Array | Buffer | string;

/**
 * What a node asserts: that it holds a share of this wallet, that the wallet has
 * this address and group key, and that the group has this shape.
 */
export interface Statement {
  walletId: string;
  address: string;
  groupPubkey: ByteInput;
  threshold: number;
  allIds: number[];
}

/** One node's signed Statement. */
export interface Attestation {
  /**
   * Which node signed. It is a hint for matching against a configured public
   * key and carries no authority on its own: verification recovers the signer
   * from the signature and compares.
   */
  partyId: number;
  /** 65 bytes, secp256k1 recoverable, over the statement digest. */
  signature: ByteInput;
}

/** A signer node's identity, as a caller knows it. */
export interface NodeKey {
  partyId: number;
  /**
   * The 33-byte compressed public key, learned OUT OF BAND. A caller that took
   * these from the same response it is verifying would be asking the vault
   * whether the vault is honest.
   */
  pubKey: ByteInput;
}

function toBytes(v: ByteInput, what: string): Uint8Array {
  if (typeof v === 'string') {
    let s = v.trim();
    if (s.startsWith('0x') || s.startsWith('0X')) s = s.slice(2);
    if (s.length % 2 !== 0 || (s.length > 0 && !/^[0-9a-fA-F]+$/.test(s))) {
      throw new Error(`${what} is not valid hex`);
    }
    return new Uint8Array(Buffer.from(s, 'hex'));
  }
  if (v instanceof Uint8Array) return v;
  throw new Error(`${what} must be bytes or a hex string`);
}

function toHex(b: Uint8Array): string {
  return Buffer.from(b).toString('hex');
}

function uint32(n: number, what: string): Uint8Array {
  // Go writes these as uint32 and would WRAP a value outside the range. Wrapping
  // in one implementation and throwing in the other is exactly the silent
  // divergence this port has to avoid, so anything that cannot round-trip is
  // refused on both counts.
  if (!Number.isInteger(n) || n < 0 || n > 0xffffffff) {
    throw new Error(`${what} must be an integer in [0, 2^32), got ${n}`);
  }
  const out = new Uint8Array(4);
  new DataView(out.buffer).setUint32(0, n, false);
  return out;
}

/**
 * The 32 bytes a node signs.
 *
 * Every field is length-prefixed. Without that, ("ab","c") and ("a","bc") would
 * hash identically, and an attacker who controlled two adjacent fields could
 * move the boundary between them while keeping the signature valid.
 */
export function statementDigest(s: Statement): Uint8Array {
  if (!s.walletId) throw new Error('attestation needs a wallet id');
  if (!s.address) throw new Error('attestation needs an address');
  const groupPub = toBytes(s.groupPubkey, 'attestation group key');
  if (groupPub.length !== COMPRESSED_PUBKEY_LENGTH) {
    throw new Error(
      `attestation group key must be 33 compressed bytes, got ${groupPub.length}`,
    );
  }
  if (!Number.isInteger(s.threshold) || s.threshold < 2) {
    throw new Error(`attestation threshold ${s.threshold} is below 2`);
  }
  if (s.allIds.length < s.threshold) {
    throw new Error(
      `attestation lists ${s.allIds.length} parties, below its own threshold ${s.threshold}`,
    );
  }

  // Numeric sort: the same group described in a different order is the same
  // group, and JavaScript's default sort is lexicographic — which would put 10
  // before 2 and produce a digest no signer ever signed.
  const ids = [...s.allIds].sort((a, b) => a - b);

  const parts: Uint8Array[] = [];
  const field = (b: Uint8Array) => {
    parts.push(uint32(b.length, 'field length'), b);
  };
  field(new TextEncoder().encode(DOMAIN));
  field(new TextEncoder().encode(s.walletId));
  field(new TextEncoder().encode(s.address.toLowerCase()));
  field(groupPub);
  parts.push(uint32(s.threshold, 'threshold'));
  parts.push(uint32(ids.length, 'party count'));
  for (const id of ids) parts.push(uint32(id, 'party id'));

  return keccak_256(Buffer.concat(parts));
}

/**
 * Checks that a set of configured node identities can actually carry a
 * threshold. Call it where configuration is loaded, so a bad set is caught once
 * at startup rather than per request; verifyAttestations calls it again anyway,
 * because nothing it protects is optional.
 *
 * Distinct public keys are the load-bearing part. Verification counts distinct
 * PARTY IDS, so if one key is configured under two ids — a copy-paste between
 * config entries, which nothing else in the system would ever complain about —
 * the node holding it can sign twice, be counted twice, and satisfy a 2-of-3
 * threshold on its own. The deployment looks healthy right up until that one
 * node is compromised, at which point the threshold it was supposed to have
 * never existed.
 */
export function validateNodeKeys(nodes: NodeKey[]): void {
  if (!nodes || nodes.length === 0) {
    throw new Error(
      'no node identity keys configured, so attestations cannot be verified; ' +
        "a client that skips this is trusting the frontend's word for the address",
    );
  }
  const byParty = new Set<number>();
  const byPub = new Map<string, number>();
  for (const n of nodes) {
    const pub = toBytes(n.pubKey, `node ${n.partyId} public key`);
    if (pub.length !== COMPRESSED_PUBKEY_LENGTH) {
      throw new Error(
        `node ${n.partyId} public key must be 33 compressed bytes, got ${pub.length}`,
      );
    }
    if (byParty.has(n.partyId)) {
      throw new Error(
        `party ${n.partyId} is configured more than once; each party id must name one node`,
      );
    }
    const other = byPub.get(toHex(pub));
    if (other !== undefined) {
      throw new Error(
        `parties ${other} and ${n.partyId} are configured with the same public key, ` +
          'so one node would satisfy the threshold by itself',
      );
    }
    byParty.add(n.partyId);
    byPub.set(toHex(pub), n.partyId);
  }
}

/**
 * Throws unless at least `threshold` DISTINCT configured nodes attested to this
 * statement.
 *
 * Counting distinct parties is the whole point. A frontend that could replay one
 * node's attestation, or sign several itself, would reproduce the failure this
 * exists to detect — so each signature must recover to a different configured
 * key, and a party that appears twice counts once.
 *
 * It throws rather than returning a verdict because a verdict gets ignored and
 * the funds go to the address anyway.
 */
export function verifyAttestations(
  s: Statement,
  attestations: Attestation[],
  nodes: NodeKey[],
  threshold: number,
): void {
  if (!Number.isInteger(threshold) || threshold < 2) {
    throw new Error(`attestation threshold ${threshold} is below 2`);
  }
  // Counting distinct party ids only means something if the ids name distinct
  // keys, so the configuration is checked before it is counted with.
  validateNodeKeys(nodes);
  const digest = statementDigest(s);

  const byParty = new Map<number, string>();
  for (const n of nodes) {
    byParty.set(n.partyId, toHex(toBytes(n.pubKey, `node ${n.partyId} public key`)));
  }

  const seen = new Set<number>();
  for (const a of attestations ?? []) {
    if (!a) continue;
    let sig: Uint8Array;
    try {
      sig = toBytes(a.signature, `attestation from party ${a.partyId}`);
    } catch {
      continue;
    }
    if (sig.length !== SIGNATURE_LENGTH) continue;
    const want = byParty.get(a.partyId);
    if (want === undefined) {
      // An attestation from a party the caller does not know about proves
      // nothing; counting it would let the frontend invent signers.
      continue;
    }
    let recovered: string;
    try {
      recovered = toHex(
        secp256k1.Signature.fromCompact(sig.subarray(0, 64))
          .addRecoveryBit(sig[64])
          .recoverPublicKey(digest)
          .toRawBytes(true),
      );
    } catch {
      continue;
    }
    if (recovered !== want) continue;
    seen.add(a.partyId);
  }

  if (seen.size < threshold) {
    throw new Error(
      `wallet ${s.address} carries ${seen.size} valid node attestations, below its threshold of ${threshold}; ` +
        'the address may not be backed by a real threshold sharing',
    );
  }
}

/**
 * Parses node identities from a configuration string of `partyId:pubkeyHex`
 * pairs separated by commas or whitespace, e.g.
 * `1:02ab…,2:03cd…,3:02ef…`.
 *
 * This exists so callers can put the keys in an environment variable without
 * each one inventing its own parser — and, more to the point, without any of
 * them being tempted to read the keys out of the vault's own response.
 */
export function parseNodeKeys(spec: string): NodeKey[] {
  const out: NodeKey[] = [];
  for (const entry of spec.split(/[,\s]+/)) {
    const e = entry.trim();
    if (!e) continue;
    const sep = e.indexOf(':');
    if (sep < 0) {
      throw new Error(`node key "${e}" is not in partyId:publicKeyHex form`);
    }
    const partyId = Number(e.slice(0, sep));
    if (!Number.isInteger(partyId) || partyId < 0) {
      throw new Error(`node key "${e}" has a party id that is not a non-negative integer`);
    }
    out.push({ partyId, pubKey: toBytes(e.slice(sep + 1), `node ${partyId} public key`) });
  }
  // An empty or whitespace-only setting means somebody meant to configure
  // verification and did not. Returning [] would disable it silently, which is
  // the worst outcome available: not configuring it at all leaves you knowing
  // you trust the frontend, while configuring it and getting nothing leaves you
  // certain of a guarantee you do not have.
  if (out.length === 0) {
    throw new Error('node key configuration is empty, which would disable attestation verification');
  }
  validateNodeKeys(out);
  return out;
}
