// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.36.0
// source: proto/vault/v1/vault.proto

package vaultv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VaultService_Create_FullMethodName        = "/vault.v1.VaultService/Create"
	VaultService_GetWallet_FullMethodName     = "/vault.v1.VaultService/GetWallet"
	VaultService_SignByWallet_FullMethodName  = "/vault.v1.VaultService/SignByWallet"
	VaultService_SignByAddress_FullMethodName = "/vault.v1.VaultService/SignByAddress"
	VaultService_TypedData_FullMethodName     = "/vault.v1.VaultService/TypedData"
	VaultService_SetCode_FullMethodName       = "/vault.v1.VaultService/SetCode"
)

// VaultServiceClient is the client API for VaultService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Import is gone. Threshold custody has no trusted-dealer or resharing
// primitive, so an externally-generated full key cannot be split into a t-of-n
// sharing, and accepting one would put a whole private key inside a system whose
// guarantee is that no node holds one. Clients still calling it receive
// UNIMPLEMENTED from gRPC itself. Wallets are created via DKG with Create.
type VaultServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error)
	SignByWallet(ctx context.Context, in *SignByWalletRequest, opts ...grpc.CallOption) (*SignByWalletResponse, error)
	SignByAddress(ctx context.Context, in *SignByAddressRequest, opts ...grpc.CallOption) (*SignByAddressResponse, error)
	TypedData(ctx context.Context, in *TypedDataRequest, opts ...grpc.CallOption) (*RSVResponse, error)
	SetCode(ctx context.Context, in *SetCodeRequest, opts ...grpc.CallOption) (*RSVResponse, error)
}

type vaultServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVaultServiceClient(cc grpc.ClientConnInterface) VaultServiceClient {
	return &vaultServiceClient{cc}
}

func (c *vaultServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, VaultService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletResponse)
	err := c.cc.Invoke(ctx, VaultService_GetWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) SignByWallet(ctx context.Context, in *SignByWalletRequest, opts ...grpc.CallOption) (*SignByWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignByWalletResponse)
	err := c.cc.Invoke(ctx, VaultService_SignByWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) SignByAddress(ctx context.Context, in *SignByAddressRequest, opts ...grpc.CallOption) (*SignByAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignByAddressResponse)
	err := c.cc.Invoke(ctx, VaultService_SignByAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) TypedData(ctx context.Context, in *TypedDataRequest, opts ...grpc.CallOption) (*RSVResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RSVResponse)
	err := c.cc.Invoke(ctx, VaultService_TypedData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) SetCode(ctx context.Context, in *SetCodeRequest, opts ...grpc.CallOption) (*RSVResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RSVResponse)
	err := c.cc.Invoke(ctx, VaultService_SetCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VaultServiceServer is the server API for VaultService service.
// All implementations must embed UnimplementedVaultServiceServer
// for forward compatibility.
//
// Import is gone. Threshold custody has no trusted-dealer or resharing
// primitive, so an externally-generated full key cannot be split into a t-of-n
// sharing, and accepting one would put a whole private key inside a system whose
// guarantee is that no node holds one. Clients still calling it receive
// UNIMPLEMENTED from gRPC itself. Wallets are created via DKG with Create.
type VaultServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	GetWallet(context.Context, *GetWalletRequest) (*GetWalletResponse, error)
	SignByWallet(context.Context, *SignByWalletRequest) (*SignByWalletResponse, error)
	SignByAddress(context.Context, *SignByAddressRequest) (*SignByAddressResponse, error)
	TypedData(context.Context, *TypedDataRequest) (*RSVResponse, error)
	SetCode(context.Context, *SetCodeRequest) (*RSVResponse, error)
	mustEmbedUnimplementedVaultServiceServer()
}

// UnimplementedVaultServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVaultServiceServer struct{}

func (UnimplementedVaultServiceServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedVaultServiceServer) GetWallet(context.Context, *GetWalletRequest) (*GetWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWallet not implemented")
}
func (UnimplementedVaultServiceServer) SignByWallet(context.Context, *SignByWalletRequest) (*SignByWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignByWallet not implemented")
}
func (UnimplementedVaultServiceServer) SignByAddress(context.Context, *SignByAddressRequest) (*SignByAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignByAddress not implemented")
}
func (UnimplementedVaultServiceServer) TypedData(context.Context, *TypedDataRequest) (*RSVResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TypedData not implemented")
}
func (UnimplementedVaultServiceServer) SetCode(context.Context, *SetCodeRequest) (*RSVResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCode not implemented")
}
func (UnimplementedVaultServiceServer) mustEmbedUnimplementedVaultServiceServer() {}
func (UnimplementedVaultServiceServer) testEmbeddedByValue()                      {}

// UnsafeVaultServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VaultServiceServer will
// result in compilation errors.
type UnsafeVaultServiceServer interface {
	mustEmbedUnimplementedVaultServiceServer()
}

func RegisterVaultServiceServer(s grpc.ServiceRegistrar, srv VaultServiceServer) {
	// If the following call panics, it indicates UnimplementedVaultServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VaultService_ServiceDesc, srv)
}

func _VaultService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_GetWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).GetWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_GetWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).GetWallet(ctx, req.(*GetWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_SignByWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignByWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).SignByWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_SignByWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).SignByWallet(ctx, req.(*SignByWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_SignByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).SignByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_SignByAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).SignByAddress(ctx, req.(*SignByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_TypedData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TypedDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).TypedData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_TypedData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).TypedData(ctx, req.(*TypedDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_SetCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).SetCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_SetCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).SetCode(ctx, req.(*SetCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VaultService_ServiceDesc is the grpc.ServiceDesc for VaultService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VaultService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vault.v1.VaultService",
	HandlerType: (*VaultServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _VaultService_Create_Handler,
		},
		{
			MethodName: "GetWallet",
			Handler:    _VaultService_GetWallet_Handler,
		},
		{
			MethodName: "SignByWallet",
			Handler:    _VaultService_SignByWallet_Handler,
		},
		{
			MethodName: "SignByAddress",
			Handler:    _VaultService_SignByAddress_Handler,
		},
		{
			MethodName: "TypedData",
			Handler:    _VaultService_TypedData_Handler,
		},
		{
			MethodName: "SetCode",
			Handler:    _VaultService_SetCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/vault/v1/vault.proto",
}
