// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: proto/vault/v1/vault.proto

package vaultv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// All wallets use threshold ECDSA. The former `version` field selected between
// local single-key and threshold custody; local custody is gone, so there is
// nothing left to select and the field is reserved rather than reused.
type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markup        string                 `protobuf:"bytes,1,opt,name=markup,proto3" json:"markup,omitempty"`
	WalletId      string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_proto_vault_v1_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_v1_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_vault_v1_vault_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetMarkup() string {
	if x != nil {
		return x.Markup
	}
	return ""
}

func (x *CreateRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

// WalletAttestation is one signer node's signed assertion that it holds a share
// of this wallet.
//
// Verify these CLIENT-SIDE against node public keys learned out of band. A
// client that skips this is taking the frontend's word that the address is
// backed by a real threshold sharing — and a compromised frontend can generate a
// key it alone knows and hand out its address instead.
type WalletAttestation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       int32                  `protobuf:"varint,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletAttestation) Reset() {
	*x = WalletAttestation{}
	mi := &file_proto_vault_v1_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletAttestation) ProtoMessage() {}

func (x *WalletAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_v1_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletAttestation.ProtoReflect.Descriptor instead.
func (*WalletAttestation) Descriptor() ([]byte, []int) {
	return file_proto_vault_v1_vault_proto_rawDescGZIP(), []int{1}
}

func (x *WalletAttestation) GetPartyId() int32 {
	if x != nil {
		return x.PartyId
	}
	return 0
}

func (x *WalletAttestation) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type CreateResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WalletId    string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	EcdsaPubkey string                 `protobuf:"bytes,2,opt,name=ecdsa_pubkey,json=ecdsaPubkey,proto3" json:"ecdsa_pubkey,omitempty"`
	// attestations is populated on a distributed deployment: one entry per signer
	// node that confirmed it holds a share of this wallet. Empty on a single-host
	// deployment, where there is nothing independent to attest.
	//
	// A client that receives fewer than `threshold` valid attestations should
	// treat the address as unverified and NOT fund it.
	Attestations []*WalletAttestation `protobuf:"bytes,3,rep,name=attestations,proto3" json:"attestations,omitempty"`
	// group_pubkey is the 33-byte compressed group key. It is part of what the
	// attestations commit to, so a client needs it to check them.
	GroupPubkey   []byte  `protobuf:"bytes,4,opt,name=group_pubkey,json=groupPubkey,proto3" json:"group_pubkey,omitempty"`
	Threshold     int32   `protobuf:"varint,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	AllIds        []int32 `protobuf:"varint,6,rep,packed,name=all_ids,json=allIds,proto3" json:"all_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_proto_vault_v1_vault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_v1_vault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_vault_v1_vault_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *CreateResponse) GetEcdsaPubkey() string {
	if x != nil {
		return x.EcdsaPubkey
	}
	return ""
}

func (x *CreateResponse) GetAttestations() []*WalletAttestation {
	if x != nil {
		return x.Attestations
	}
	return nil
}

func (x *CreateResponse) GetGroupPubkey() []byte {
	if x != nil {
		return x.GroupPubkey
	}
	return nil
}

func (x *CreateResponse) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *CreateResponse) GetAllIds() []int32 {
	if x != nil {
		return x.AllIds
	}
	return nil
}

// GetWallet resolves the public identity of an existing threshold wallet. It
// never returns key material. The same identity is returned by an idempotent
// Create retry.
type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_proto_vault_v1_vault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_v1_vault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_proto_vault_v1_vault_proto_rawDescGZIP(), []int{3}
}

func (x *GetWalletRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type GetWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Markup        string                 `protobuf:"bytes,2,opt,name=markup,proto3" json:"markup,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	GroupPubkey   []byte                 `protobuf:"bytes,4,opt,name=group_pubkey,json=groupPubkey,proto3" json:"group_pubkey,omitempty"`
	Threshold     int32                  `protobuf:"varint,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	AllIds        []int32                `protobuf:"varint,6,rep,packed,name=all_ids,json=allIds,proto3" json:"all_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletResponse) Reset() {
	*x = GetWalletResponse{}
	mi := &file_proto_vault_v1_vault_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletResponse) ProtoMessage() {}

func (x *GetWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_v1_vault_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletResponse.ProtoReflect.Descriptor instead.
func (*GetWalletResponse) Descriptor() ([]byte, []int) {
	return file_proto_vault_v1_vault_proto_rawDescGZIP(), []int{4}
}

func (x *GetWalletResponse) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *GetWalletResponse) GetMarkup() string {
	if x != nil {
		return x.Markup
	}
	return ""
}

func (x *GetWalletResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetWalletResponse) GetGroupPubkey() []byte {
	if x != nil {
		return x.GroupPubkey
	}
	return nil
}

func (x *GetWalletResponse) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *GetWalletResponse) GetAllIds() []int32 {
	if x != nil {
		return x.AllIds
	}
	return nil
}

type SignByWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Network       string                 `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	ChainId       []byte                 `protobuf:"bytes,4,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Transaction   []byte                 `protobuf:"bytes,6,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignByWalletRequest) Reset() {
	*x = SignByWalletRequest{}
	mi := &file_proto_vault_v1_vault_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignByWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignByWalletRequest) ProtoMessage() {}

func (x *SignByWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_v1_vault_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignByWalletRequest.ProtoReflect.Descriptor instead.
func (*SignByWalletRequest) Descriptor() ([]byte, []int) {
	return file_proto_vault_v1_vault_proto_rawDescGZIP(), []int{5}
}

func (x *SignByWalletRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *SignByWalletRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SignByWalletRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *SignByWalletRequest) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *SignByWalletRequest) GetTransaction() []byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type SignByWalletResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SignedTransaction []byte                 `protobuf:"bytes,1,opt,name=signed_transaction,json=signedTransaction,proto3" json:"signed_transaction,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignByWalletResponse) Reset() {
	*x = SignByWalletResponse{}
	mi := &file_proto_vault_v1_vault_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignByWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignByWalletResponse) ProtoMessage() {}

func (x *SignByWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_v1_vault_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignByWalletResponse.ProtoReflect.Descriptor instead.
func (*SignByWalletResponse) Descriptor() ([]byte, []int) {
	return file_proto_vault_v1_vault_proto_rawDescGZIP(), []int{6}
}

func (x *SignByWalletResponse) GetSignedTransaction() []byte {
	if x != nil {
		return x.SignedTransaction
	}
	return nil
}

type SignByAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Network       string                 `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	ChainId       []byte                 `protobuf:"bytes,4,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Transaction   []byte                 `protobuf:"bytes,6,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignByAddressRequest) Reset() {
	*x = SignByAddressRequest{}
	mi := &file_proto_vault_v1_vault_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignByAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignByAddressRequest) ProtoMessage() {}

func (x *SignByAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_v1_vault_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignByAddressRequest.ProtoReflect.Descriptor instead.
func (*SignByAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_vault_v1_vault_proto_rawDescGZIP(), []int{7}
}

func (x *SignByAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SignByAddressRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SignByAddressRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *SignByAddressRequest) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *SignByAddressRequest) GetTransaction() []byte {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type SignByAddressResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SignedTransaction []byte                 `protobuf:"bytes,1,opt,name=signed_transaction,json=signedTransaction,proto3" json:"signed_transaction,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignByAddressResponse) Reset() {
	*x = SignByAddressResponse{}
	mi := &file_proto_vault_v1_vault_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignByAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignByAddressResponse) ProtoMessage() {}

func (x *SignByAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_v1_vault_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignByAddressResponse.ProtoReflect.Descriptor instead.
func (*SignByAddressResponse) Descriptor() ([]byte, []int) {
	return file_proto_vault_v1_vault_proto_rawDescGZIP(), []int{8}
}

func (x *SignByAddressResponse) GetSignedTransaction() []byte {
	if x != nil {
		return x.SignedTransaction
	}
	return nil
}

type TypedDataRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Network   string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	// chain_id is routing and audit metadata only; it does NOT enter the signed
	// pre-image. EIP-712 already carries the chain id inside the domain, and the
	// vault signs keccak(0x19 || 0x01 || domain_separator || typed_data_hash) —
	// so this field cannot change what gets signed and is optional.
	//
	// Authorization for this RPC attaches to domain_separator, which the server
	// matches against the calling credential's allowed-typed-data-domains.
	ChainId []byte `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Address []byte `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	// domain_separator and typed_data_hash are each exactly 32 bytes; the server
	// rejects any other length rather than hashing a differently-shaped pre-image.
	DomainSeparator []byte `protobuf:"bytes,5,opt,name=domain_separator,json=domainSeparator,proto3" json:"domain_separator,omitempty"`
	TypedDataHash   []byte `protobuf:"bytes,6,opt,name=typed_data_hash,json=typedDataHash,proto3" json:"typed_data_hash,omitempty"`
	// action describes WHAT is being signed, so the server can authorize it rather
	// than only sign it. Optional; see HyperliquidAction.
	Action *HyperliquidAction `protobuf:"bytes,7,opt,name=action,proto3" json:"action,omitempty"`
	// message describes a NON-Hyperliquid EIP-712 payload the same way: a
	// registered struct type over an explicit domain. At most one of action,
	// message and calibur may be set — multiple descriptions of one digest cannot
	// all be checked, and picking one would let a caller attach a benign
	// description beside the real one.
	//
	// It exists because "describe what you are signing" cannot be a Hyperliquid-only
	// rule. A vault that enforced descriptions but could only describe one
	// application would have to exempt every other payload, and an exemption is a
	// hole whatever it is called. EIP-3009 is the second family; the shape below is
	// general, so the third costs a type registration and no protocol change.
	Message *Eip712Message `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	// calibur is the dedicated, fully structured representation of a Calibur
	// SignedBatchedCall. At most one of action, message and calibur may be set.
	Calibur       *CaliburSignedBatchedCall `protobuf:"bytes,9,opt,name=calibur,proto3" json:"calibur,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypedDataRequest) Reset() {
	*x = TypedDataRequest{}
	mi := &file_proto_vault_v1_vault_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypedDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedDataRequest) ProtoMessage() {}

func (x *TypedDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_v1_vault_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedDataRequest.ProtoReflect.Descriptor instead.
func (*TypedDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_vault_v1_vault_proto_rawDescGZIP(), []int{9}
}

func (x *TypedDataRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TypedDataRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *TypedDataRequest) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *TypedDataRequest) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *TypedDataRequest) GetDomainSeparator() []byte {
	if x != nil {
		return x.DomainSeparator
	}
	return nil
}

func (x *TypedDataRequest) GetTypedDataHash() []byte {
	if x != nil {
		return x.TypedDataHash
	}
	return nil
}

func (x *TypedDataRequest) GetAction() *HyperliquidAction {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *TypedDataRequest) GetMessage() *Eip712Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *TypedDataRequest) GetCalibur() *CaliburSignedBatchedCall {
	if x != nil {
		return x.Calibur
	}
	return nil
}

// Eip712Message is a described EIP-712 struct: which registered type it is, the
// domain PARTS, and the value of every field that type signs over.
//
// The domain travels in PARTS and never as a separator, and that is the whole
// point rather than a detail. A caller that hands over 32 bytes has ASSERTED a
// domain; a caller that hands over name, version, chainId and verifyingContract
// has stated one the vault rebuilds and checks against the separator being
// signed. So verifyingContract — which for a token authorization IS the token —
// becomes a verified field instead of a claim, and a policy over it is a policy
// over something real.
type Eip712Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// primary_type is the registered struct, e.g. "TransferWithAuthorization".
	// A type this build cannot describe is REFUSED, never passed through: a
	// payload the vault cannot check is one it must not vouch for.
	PrimaryType string        `protobuf:"bytes,1,opt,name=primary_type,json=primaryType,proto3" json:"primary_type,omitempty"`
	Domain      *Eip712Domain `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	// fields holds every field of primary_type, keyed by name: an address or a
	// bytes32 as 0x-prefixed hex, an integer as a DECIMAL STRING. Strings because
	// a uint256 has no lossless numeric representation here, and a rounded amount
	// would authorize a transfer nobody asked for.
	//
	// A field the type does not declare is an error, not surplus.
	Fields        map[string]string `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Eip712Message) Reset() {
	*x = Eip712Message{}
	mi := &file_proto_vault_v1_vault_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Eip712Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Eip712Message) ProtoMessage() {}

func (x *Eip712Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_v1_vault_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Eip712Message.ProtoReflect.Descriptor instead.
func (*Eip712Message) Descriptor() ([]byte, []int) {
	return file_proto_vault_v1_vault_proto_rawDescGZIP(), []int{10}
}

func (x *Eip712Message) GetPrimaryType() string {
	if x != nil {
		return x.PrimaryType
	}
	return ""
}

func (x *Eip712Message) GetDomain() *Eip712Domain {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *Eip712Message) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Eip712Domain is EIP712Domain(name,version,chainId,verifyingContract) in the
// four parts its separator is built from. chain_id is decimal for the same
// reason the fields are.
type Eip712Domain struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version           string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ChainId           string                 `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	VerifyingContract string                 `protobuf:"bytes,4,opt,name=verifying_contract,json=verifyingContract,proto3" json:"verifying_contract,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Eip712Domain) Reset() {
	*x = Eip712Domain{}
	mi := &file_proto_vault_v1_vault_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Eip712Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Eip712Domain) ProtoMessage() {}

func (x *Eip712Domain) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_v1_vault_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Eip712Domain.ProtoReflect.Descriptor instead.
func (*Eip712Domain) Descriptor() ([]byte, []int) {
	return file_proto_vault_v1_vault_proto_rawDescGZIP(), []int{11}
}

func (x *Eip712Domain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Eip712Domain) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Eip712Domain) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *Eip712Domain) GetVerifyingContract() string {
	if x != nil {
		return x.VerifyingContract
	}
	return ""
}

// CaliburCall is one call nested in Calibur's BatchedCall. Bytes keep uint256
// values lossless and bind calldata byte-for-byte to the derived digest.
type CaliburCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            []byte                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaliburCall) Reset() {
	*x = CaliburCall{}
	mi := &file_proto_vault_v1_vault_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaliburCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaliburCall) ProtoMessage() {}

func (x *CaliburCall) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_v1_vault_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaliburCall.ProtoReflect.Descriptor instead.
func (*CaliburCall) Descriptor() ([]byte, []int) {
	return file_proto_vault_v1_vault_proto_rawDescGZIP(), []int{12}
}

func (x *CaliburCall) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *CaliburCall) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CaliburCall) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// CaliburSignedBatchedCall is the complete SignedBatchedCall description. The
// vault derives Calibur's domain from chain_id, wallet and implementation,
// including the implementation salt; no opaque domain assertion is accepted.
type CaliburSignedBatchedCall struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChainId         []byte                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Wallet          []byte                 `protobuf:"bytes,2,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Implementation  []byte                 `protobuf:"bytes,3,opt,name=implementation,proto3" json:"implementation,omitempty"`
	Calls           []*CaliburCall         `protobuf:"bytes,4,rep,name=calls,proto3" json:"calls,omitempty"`
	RevertOnFailure bool                   `protobuf:"varint,5,opt,name=revert_on_failure,json=revertOnFailure,proto3" json:"revert_on_failure,omitempty"`
	Nonce           []byte                 `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	KeyHash         []byte                 `protobuf:"bytes,7,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"`
	Executor        []byte                 `protobuf:"bytes,8,opt,name=executor,proto3" json:"executor,omitempty"`
	Deadline        []byte                 `protobuf:"bytes,9,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CaliburSignedBatchedCall) Reset() {
	*x = CaliburSignedBatchedCall{}
	mi := &file_proto_vault_v1_vault_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaliburSignedBatchedCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaliburSignedBatchedCall) ProtoMessage() {}

func (x *CaliburSignedBatchedCall) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_v1_vault_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaliburSignedBatchedCall.ProtoReflect.Descriptor instead.
func (*CaliburSignedBatchedCall) Descriptor() ([]byte, []int) {
	return file_proto_vault_v1_vault_proto_rawDescGZIP(), []int{13}
}

func (x *CaliburSignedBatchedCall) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *CaliburSignedBatchedCall) GetWallet() []byte {
	if x != nil {
		return x.Wallet
	}
	return nil
}

func (x *CaliburSignedBatchedCall) GetImplementation() []byte {
	if x != nil {
		return x.Implementation
	}
	return nil
}

func (x *CaliburSignedBatchedCall) GetCalls() []*CaliburCall {
	if x != nil {
		return x.Calls
	}
	return nil
}

func (x *CaliburSignedBatchedCall) GetRevertOnFailure() bool {
	if x != nil {
		return x.RevertOnFailure
	}
	return false
}

func (x *CaliburSignedBatchedCall) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *CaliburSignedBatchedCall) GetKeyHash() []byte {
	if x != nil {
		return x.KeyHash
	}
	return nil
}

func (x *CaliburSignedBatchedCall) GetExecutor() []byte {
	if x != nil {
		return x.Executor
	}
	return nil
}

func (x *CaliburSignedBatchedCall) GetDeadline() []byte {
	if x != nil {
		return x.Deadline
	}
	return nil
}

// HyperliquidAction is the structured form of an L1 action, so the vault can
// apply policy to what is actually being signed instead of to an opaque hash.
//
// The vault does NOT re-encode this. action_msgpack is the CALLER'S OWN encoding
// — the exact bytes it is about to hash — and the vault checks that those bytes
// derive the domain_separator and typed_data_hash in this same request. That
// makes the binding cryptographic rather than declarative: a caller cannot
// describe one action and have another signed, because the description and the
// signature pre-image are the same bytes.
//
// It also means no encoder agreement is needed. An earlier attempt required the
// vault to reproduce the SDK's msgpack exactly — insertion-ordered map keys,
// compact ints, str16-to-str8 rewriting — and stalled there. Nothing here
// depends on that.
type HyperliquidAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// action_msgpack is the caller's msgpack encoding of the action object.
	ActionMsgpack []byte `protobuf:"bytes,1,opt,name=action_msgpack,json=actionMsgpack,proto3" json:"action_msgpack,omitempty"`
	// nonce is appended big-endian when computing the action hash.
	Nonce uint64 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// vault_address is the sub-account this acts on behalf of, or empty.
	VaultAddress string `protobuf:"bytes,3,opt,name=vault_address,json=vaultAddress,proto3" json:"vault_address,omitempty"`
	// expires_after is optional; has_expires_after distinguishes "zero" from
	// "absent", which produce different action hashes.
	ExpiresAfter    uint64 `protobuf:"varint,4,opt,name=expires_after,json=expiresAfter,proto3" json:"expires_after,omitempty"`
	HasExpiresAfter bool   `protobuf:"varint,5,opt,name=has_expires_after,json=hasExpiresAfter,proto3" json:"has_expires_after,omitempty"`
	// is_mainnet selects the phantom agent source tag. It does NOT change the
	// domain: the L1 domain's chainId is 1337 on both networks.
	IsMainnet     bool `protobuf:"varint,6,opt,name=is_mainnet,json=isMainnet,proto3" json:"is_mainnet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HyperliquidAction) Reset() {
	*x = HyperliquidAction{}
	mi := &file_proto_vault_v1_vault_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HyperliquidAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HyperliquidAction) ProtoMessage() {}

func (x *HyperliquidAction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_v1_vault_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HyperliquidAction.ProtoReflect.Descriptor instead.
func (*HyperliquidAction) Descriptor() ([]byte, []int) {
	return file_proto_vault_v1_vault_proto_rawDescGZIP(), []int{14}
}

func (x *HyperliquidAction) GetActionMsgpack() []byte {
	if x != nil {
		return x.ActionMsgpack
	}
	return nil
}

func (x *HyperliquidAction) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *HyperliquidAction) GetVaultAddress() string {
	if x != nil {
		return x.VaultAddress
	}
	return ""
}

func (x *HyperliquidAction) GetExpiresAfter() uint64 {
	if x != nil {
		return x.ExpiresAfter
	}
	return 0
}

func (x *HyperliquidAction) GetHasExpiresAfter() bool {
	if x != nil {
		return x.HasExpiresAfter
	}
	return false
}

func (x *HyperliquidAction) GetIsMainnet() bool {
	if x != nil {
		return x.IsMainnet
	}
	return false
}

type SetCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Network       string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	ChainId       []byte                 `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Address       []byte                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Delegate      []byte                 `protobuf:"bytes,5,opt,name=delegate,proto3" json:"delegate,omitempty"`
	Nonce         uint64                 `protobuf:"varint,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCodeRequest) Reset() {
	*x = SetCodeRequest{}
	mi := &file_proto_vault_v1_vault_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCodeRequest) ProtoMessage() {}

func (x *SetCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_v1_vault_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCodeRequest.ProtoReflect.Descriptor instead.
func (*SetCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_vault_v1_vault_proto_rawDescGZIP(), []int{15}
}

func (x *SetCodeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SetCodeRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *SetCodeRequest) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *SetCodeRequest) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *SetCodeRequest) GetDelegate() []byte {
	if x != nil {
		return x.Delegate
	}
	return nil
}

func (x *SetCodeRequest) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type RSVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             []byte                 `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	S             []byte                 `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	V             int32                  `protobuf:"varint,3,opt,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RSVResponse) Reset() {
	*x = RSVResponse{}
	mi := &file_proto_vault_v1_vault_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RSVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSVResponse) ProtoMessage() {}

func (x *RSVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_v1_vault_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSVResponse.ProtoReflect.Descriptor instead.
func (*RSVResponse) Descriptor() ([]byte, []int) {
	return file_proto_vault_v1_vault_proto_rawDescGZIP(), []int{16}
}

func (x *RSVResponse) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *RSVResponse) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *RSVResponse) GetV() int32 {
	if x != nil {
		return x.V
	}
	return 0
}

var File_proto_vault_v1_vault_proto protoreflect.FileDescriptor

const file_proto_vault_v1_vault_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/vault/v1/vault.proto\x12\bvault.v1\"S\n" +
	"\rCreateRequest\x12\x16\n" +
	"\x06markup\x18\x01 \x01(\tR\x06markup\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletIdJ\x04\b\x03\x10\x04R\aversion\"L\n" +
	"\x11WalletAttestation\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\x05R\apartyId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xeb\x01\n" +
	"\x0eCreateResponse\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12!\n" +
	"\fecdsa_pubkey\x18\x02 \x01(\tR\vecdsaPubkey\x12?\n" +
	"\fattestations\x18\x03 \x03(\v2\x1b.vault.v1.WalletAttestationR\fattestations\x12!\n" +
	"\fgroup_pubkey\x18\x04 \x01(\fR\vgroupPubkey\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x05R\tthreshold\x12\x17\n" +
	"\aall_ids\x18\x06 \x03(\x05R\x06allIds\"/\n" +
	"\x10GetWalletRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"\xbc\x01\n" +
	"\x11GetWalletResponse\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x16\n" +
	"\x06markup\x18\x02 \x01(\tR\x06markup\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12!\n" +
	"\fgroup_pubkey\x18\x04 \x01(\fR\vgroupPubkey\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x05R\tthreshold\x12\x17\n" +
	"\aall_ids\x18\x06 \x03(\x05R\x06allIds\"\xa8\x01\n" +
	"\x13SignByWalletRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x12\x19\n" +
	"\bchain_id\x18\x04 \x01(\fR\achainId\x12 \n" +
	"\vtransaction\x18\x06 \x01(\fR\vtransaction\"E\n" +
	"\x14SignByWalletResponse\x12-\n" +
	"\x12signed_transaction\x18\x01 \x01(\fR\x11signedTransaction\"\xa6\x01\n" +
	"\x14SignByAddressRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x12\x19\n" +
	"\bchain_id\x18\x04 \x01(\fR\achainId\x12 \n" +
	"\vtransaction\x18\x06 \x01(\fR\vtransaction\"F\n" +
	"\x15SignByAddressResponse\x12-\n" +
	"\x12signed_transaction\x18\x01 \x01(\fR\x11signedTransaction\"\xf9\x02\n" +
	"\x10TypedDataRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x19\n" +
	"\bchain_id\x18\x03 \x01(\fR\achainId\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\fR\aaddress\x12)\n" +
	"\x10domain_separator\x18\x05 \x01(\fR\x0fdomainSeparator\x12&\n" +
	"\x0ftyped_data_hash\x18\x06 \x01(\fR\rtypedDataHash\x123\n" +
	"\x06action\x18\a \x01(\v2\x1b.vault.v1.HyperliquidActionR\x06action\x121\n" +
	"\amessage\x18\b \x01(\v2\x17.vault.v1.Eip712MessageR\amessage\x12<\n" +
	"\acalibur\x18\t \x01(\v2\".vault.v1.CaliburSignedBatchedCallR\acalibur\"\xda\x01\n" +
	"\rEip712Message\x12!\n" +
	"\fprimary_type\x18\x01 \x01(\tR\vprimaryType\x12.\n" +
	"\x06domain\x18\x02 \x01(\v2\x16.vault.v1.Eip712DomainR\x06domain\x12;\n" +
	"\x06fields\x18\x03 \x03(\v2#.vault.v1.Eip712Message.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x01\n" +
	"\fEip712Domain\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x19\n" +
	"\bchain_id\x18\x03 \x01(\tR\achainId\x12-\n" +
	"\x12verifying_contract\x18\x04 \x01(\tR\x11verifyingContract\"G\n" +
	"\vCaliburCall\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\fR\x02to\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xb7\x02\n" +
	"\x18CaliburSignedBatchedCall\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\fR\achainId\x12\x16\n" +
	"\x06wallet\x18\x02 \x01(\fR\x06wallet\x12&\n" +
	"\x0eimplementation\x18\x03 \x01(\fR\x0eimplementation\x12+\n" +
	"\x05calls\x18\x04 \x03(\v2\x15.vault.v1.CaliburCallR\x05calls\x12*\n" +
	"\x11revert_on_failure\x18\x05 \x01(\bR\x0frevertOnFailure\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\fR\x05nonce\x12\x19\n" +
	"\bkey_hash\x18\a \x01(\fR\akeyHash\x12\x1a\n" +
	"\bexecutor\x18\b \x01(\fR\bexecutor\x12\x1a\n" +
	"\bdeadline\x18\t \x01(\fR\bdeadline\"\xe5\x01\n" +
	"\x11HyperliquidAction\x12%\n" +
	"\x0eaction_msgpack\x18\x01 \x01(\fR\ractionMsgpack\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x04R\x05nonce\x12#\n" +
	"\rvault_address\x18\x03 \x01(\tR\fvaultAddress\x12#\n" +
	"\rexpires_after\x18\x04 \x01(\x04R\fexpiresAfter\x12*\n" +
	"\x11has_expires_after\x18\x05 \x01(\bR\x0fhasExpiresAfter\x12\x1d\n" +
	"\n" +
	"is_mainnet\x18\x06 \x01(\bR\tisMainnet\"\xb0\x01\n" +
	"\x0eSetCodeRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x19\n" +
	"\bchain_id\x18\x03 \x01(\fR\achainId\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\fR\aaddress\x12\x1a\n" +
	"\bdelegate\x18\x05 \x01(\fR\bdelegate\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\x04R\x05nonce\"7\n" +
	"\vRSVResponse\x12\f\n" +
	"\x01r\x18\x01 \x01(\fR\x01r\x12\f\n" +
	"\x01s\x18\x02 \x01(\fR\x01s\x12\f\n" +
	"\x01v\x18\x03 \x01(\x05R\x01v2\xae\x03\n" +
	"\fVaultService\x12;\n" +
	"\x06Create\x12\x17.vault.v1.CreateRequest\x1a\x18.vault.v1.CreateResponse\x12D\n" +
	"\tGetWallet\x12\x1a.vault.v1.GetWalletRequest\x1a\x1b.vault.v1.GetWalletResponse\x12M\n" +
	"\fSignByWallet\x12\x1d.vault.v1.SignByWalletRequest\x1a\x1e.vault.v1.SignByWalletResponse\x12P\n" +
	"\rSignByAddress\x12\x1e.vault.v1.SignByAddressRequest\x1a\x1f.vault.v1.SignByAddressResponse\x12>\n" +
	"\tTypedData\x12\x1a.vault.v1.TypedDataRequest\x1a\x15.vault.v1.RSVResponse\x12:\n" +
	"\aSetCode\x12\x18.vault.v1.SetCodeRequest\x1a\x15.vault.v1.RSVResponseBEZCgithub.com/hypercyber8/hypercyber-signer-sdk/proto/vault/v1;vaultv1b\x06proto3"

var (
	file_proto_vault_v1_vault_proto_rawDescOnce sync.Once
	file_proto_vault_v1_vault_proto_rawDescData []byte
)

func file_proto_vault_v1_vault_proto_rawDescGZIP() []byte {
	file_proto_vault_v1_vault_proto_rawDescOnce.Do(func() {
		file_proto_vault_v1_vault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vault_v1_vault_proto_rawDesc), len(file_proto_vault_v1_vault_proto_rawDesc)))
	})
	return file_proto_vault_v1_vault_proto_rawDescData
}

var file_proto_vault_v1_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_vault_v1_vault_proto_goTypes = []any{
	(*CreateRequest)(nil),            // 0: vault.v1.CreateRequest
	(*WalletAttestation)(nil),        // 1: vault.v1.WalletAttestation
	(*CreateResponse)(nil),           // 2: vault.v1.CreateResponse
	(*GetWalletRequest)(nil),         // 3: vault.v1.GetWalletRequest
	(*GetWalletResponse)(nil),        // 4: vault.v1.GetWalletResponse
	(*SignByWalletRequest)(nil),      // 5: vault.v1.SignByWalletRequest
	(*SignByWalletResponse)(nil),     // 6: vault.v1.SignByWalletResponse
	(*SignByAddressRequest)(nil),     // 7: vault.v1.SignByAddressRequest
	(*SignByAddressResponse)(nil),    // 8: vault.v1.SignByAddressResponse
	(*TypedDataRequest)(nil),         // 9: vault.v1.TypedDataRequest
	(*Eip712Message)(nil),            // 10: vault.v1.Eip712Message
	(*Eip712Domain)(nil),             // 11: vault.v1.Eip712Domain
	(*CaliburCall)(nil),              // 12: vault.v1.CaliburCall
	(*CaliburSignedBatchedCall)(nil), // 13: vault.v1.CaliburSignedBatchedCall
	(*HyperliquidAction)(nil),        // 14: vault.v1.HyperliquidAction
	(*SetCodeRequest)(nil),           // 15: vault.v1.SetCodeRequest
	(*RSVResponse)(nil),              // 16: vault.v1.RSVResponse
	nil,                              // 17: vault.v1.Eip712Message.FieldsEntry
}
var file_proto_vault_v1_vault_proto_depIdxs = []int32{
	1,  // 0: vault.v1.CreateResponse.attestations:type_name -> vault.v1.WalletAttestation
	14, // 1: vault.v1.TypedDataRequest.action:type_name -> vault.v1.HyperliquidAction
	10, // 2: vault.v1.TypedDataRequest.message:type_name -> vault.v1.Eip712Message
	13, // 3: vault.v1.TypedDataRequest.calibur:type_name -> vault.v1.CaliburSignedBatchedCall
	11, // 4: vault.v1.Eip712Message.domain:type_name -> vault.v1.Eip712Domain
	17, // 5: vault.v1.Eip712Message.fields:type_name -> vault.v1.Eip712Message.FieldsEntry
	12, // 6: vault.v1.CaliburSignedBatchedCall.calls:type_name -> vault.v1.CaliburCall
	0,  // 7: vault.v1.VaultService.Create:input_type -> vault.v1.CreateRequest
	3,  // 8: vault.v1.VaultService.GetWallet:input_type -> vault.v1.GetWalletRequest
	5,  // 9: vault.v1.VaultService.SignByWallet:input_type -> vault.v1.SignByWalletRequest
	7,  // 10: vault.v1.VaultService.SignByAddress:input_type -> vault.v1.SignByAddressRequest
	9,  // 11: vault.v1.VaultService.TypedData:input_type -> vault.v1.TypedDataRequest
	15, // 12: vault.v1.VaultService.SetCode:input_type -> vault.v1.SetCodeRequest
	2,  // 13: vault.v1.VaultService.Create:output_type -> vault.v1.CreateResponse
	4,  // 14: vault.v1.VaultService.GetWallet:output_type -> vault.v1.GetWalletResponse
	6,  // 15: vault.v1.VaultService.SignByWallet:output_type -> vault.v1.SignByWalletResponse
	8,  // 16: vault.v1.VaultService.SignByAddress:output_type -> vault.v1.SignByAddressResponse
	16, // 17: vault.v1.VaultService.TypedData:output_type -> vault.v1.RSVResponse
	16, // 18: vault.v1.VaultService.SetCode:output_type -> vault.v1.RSVResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_vault_v1_vault_proto_init() }
func file_proto_vault_v1_vault_proto_init() {
	if File_proto_vault_v1_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vault_v1_vault_proto_rawDesc), len(file_proto_vault_v1_vault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vault_v1_vault_proto_goTypes,
		DependencyIndexes: file_proto_vault_v1_vault_proto_depIdxs,
		MessageInfos:      file_proto_vault_v1_vault_proto_msgTypes,
	}.Build()
	File_proto_vault_v1_vault_proto = out.File
	file_proto_vault_v1_vault_proto_goTypes = nil
	file_proto_vault_v1_vault_proto_depIdxs = nil
}
